/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.project2;

import bitcamp.project2.command.TodayTodoCommand;

public class App {
    public static void main(String[] args) {
        TodayTodoCommand todayTodoCommand = new TodayTodoCommand();
        todayTodoCommand.testData();
        todayTodoCommand.executeToday();
    }
}
