/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.project2;

import bitcamp.project2.Prompt.Prompt;
import bitcamp.project2.command.TodayTodoCommand;
import bitcamp.project2.command.TodoCommand;
import bitcamp.project2.vo.TodoList;

public class App {
    TodoList todoList = new TodoList();
    TodoCommand todoCommand = new TodoCommand(todoList);
    TodayTodoCommand todayTodoCommand = new TodayTodoCommand(todoList);
    String[] menus = {"해야할 일 추가", "목록 조회", "오늘 해야 할 일", "수정","삭제", "종료"};
    public void printMenu() {
        for (int i = 0; i < menus.length; i++) {
            System.out.printf("%d. %s\n", (i + 1), menus[i]);
        }
    }
    public void run() {
        while (true) {
            printMenu();
            String choice = Prompt.input("메뉴 >");
            try {
                int menuNo = Integer.parseInt(choice);
                switch (menuNo) {
                    case 1:
                        todoCommand.toDo();
                        break;
                    case 2:
                        todoCommand.viewTasks(); // 조회에서는 번호 없이 출력
                        break;
                    case 3:
                        todayTodoCommand.executeToday();

                        break;
                    case 4:
                        todoCommand.updateTask();
                        break;
                    case 5:
                        todoCommand.deleteTask();
                        break;
                    case 0:
                        System.out.println("종료");
                        return;
                    default:
                        System.out.println("잘못된 선택입니다. 다시 시도해주세요.");
                }
            }catch (NumberFormatException e){
                System.out.println("올바른 숫자를 입력해주세요.");
            }

        }
    }

    public static void main(String[] args) {
        App app = new App();
        app.run();
    }


}
